#!/bin/bash

build(){

 _print_error(){
  # function used to notify about errors
  echo "     [ERROR] $1"
  return 1
 }

 # read variables
 # source new ones if they are added via package updates (.pacnew file)
 ZEROTIER_CONF="/var/lib/zerotier-one/initcpio/config.ini"
 if [ -r "$ZEROTIER_CONF.pacnew" ]; then
  source "$ZEROTIER_CONF.pacnew"
 fi
 # override default values with custom ones if they are set
 if [ -r "$ZEROTIER_CONF" ]; then
  source "$ZEROTIER_CONF"
 else
 _print_error "Cannot find configuration file $ZEROTIER_CONF"
 fi

 # check variables
 if [ "$ZEROTIER_NETWORK" = "xxxxxxxxxxxxxxxx" ]; then
  _print_error "Variable ZEROTIER_NETWORK not set"
 fi
 if [ "$ZEROTIER_WAIT" -ne "$ZEROTIER_WAIT" ]; then
  _print_error "Variable ZEROTIER_WAIT is not a number"
 fi
 if [ ! -d "$ZEROTIER_HOME" ]; then
  _print_error "Cannot find home directory $ZEROTIER_HOME"
 fi
 if ! [[ "$ZEROTIER_PEER" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
  _print_error "Variable ZEROTIER_PEER is not a valid IP address"
 fi

 # create private identity file if not existent or empty
 if [ ! -s "$ZEROTIER_HOME/identity.secret" ]; then
  workDir="$PWD"
  workUmask="$(umask)"
  cd "$ZEROTIER_HOME"
  umask 177
  zerotier-idtool generate "identity.secret" >/dev/null
  umask "$workUmask"
  cd "$workDir"
 fi

 # add files to the initial ramdisk
 add_binary zerotier-one
 add_binary zerotier-cli
 if [ -r "$ZEROTIER_CONF.pacnew" ]; then
  add_file "$ZEROTIER_CONF.pacnew"
 fi
 add_file "$ZEROTIER_CONF"
 add_file "$ZEROTIER_HOME/identity.secret"

 add_runscript
}

help(){
 cat <<INFO

This hook provides connection to a ZeroTier One network to assist in the remote
unlocking of encrypted partitions. To complete the installation follow these steps as root:

0. Configure a working LAN decryption setup using either "mkinitcpio-tinyssh" or "mkinitcpio-dropbear";
1. Edit /var/lib/zerotier-one/initcpio/config.ini according to your needs;
2. Add "zerotier" to the "HOOKS" array in /etc/mkinitcpio.conf, placing it before your "tinyssh" or "dropbear" hook;
3. Add "tun" to the "MODULES" array in /etc/mkinitcpio.conf;
4. Rebuild your initial ramdisk by running 'mkinicpio -P'.

You may also need to authorize your client from https://my.zerotier.com/ the first time it connects after boot.
Be sure to have both your LAN and VPN gateway configured properly, otherwise your device may not be able
to communicate with ZeroTier One servers or be reached by other VPN peers.
It is not required to configure the ZeroTier One in the userspace, but you can do it to check for networking problems
not related to this hook (e.g. UPnP not working in your router).
See the ArchWiki for further readings remote unlocking of encrypted partitions.

INFO
}
